name: Pull request automation
on: [pull_request_target]

jobs:
  information:
    runs-on: ubuntu-latest
    env:
      DUMP_github: ${{toJSON(github)}}
      DUMP_vars: ${{toJSON(vars)}}
    steps:
      - run:
          export
          printf '\ngithub =\n%s\n' "${DUMP_github}"
          printf '\nvars =\n%s\n' "${DUMP_vars}"
