name: Pull request automation
on: [pull_request_target]

jobs:
  information:
    runs-on: ubuntu-latest
    env:
      DUMP_github: ${{toJSON(github)}}
      DUMP_vars: ${{toJSON(vars)}}
      DUMP_jobs: ${{toJSON(jobs)}}
      DUMP_steps: ${{toJSON(steps)}}
    steps:
      - run:
          export
          printf '\ngithub =\n%s\n' "${DUMP_github}"
          printf '\nvars =\n%s\n' "${DUMP_vars}"
          printf '\njobs =\n%s\n' "${DUMP_jobs}"
          printf '\nsteps =\n%s\n' "${DUMP_steps}"
